[IdyllLogo /]

[Header 
  title:"Seattle PD’s Dashcam Problem" 
  subtitle:"Visualizing 27 million frames dropped over four years" 
  author:"Matthew Conlen" 
  authorLink:"https://twitter.com/mathisonian" /]

[Section className:"article-body"]


The Seattle Police Department’s in-car video systems has been fraught
with issues since its inception. In 2011 [link href:"http://www.seattletimes.com/seattle-news/man-sues-says-spd-conceals-dash-cam-videos/" text:"a lawsuit revealed" /] that 
the department had lost 14,000 videos in 2008,
almost a fifth of the videos that were in the system at the time. In 2014 [link href:"http://spdblotter.seattle.gov/2014/04/04/spd-examining-technical-issue-with-in-car-video-system/" text:"the department reported" /] 
that an upgrade to the system on April 23, 2013 was frames of video to be lost. Most recently
the department announced that 2,283 videos recorded in July 2016 [link text:"were lost" href:"http://spdblotter.seattle.gov/2016/08/30/police-and-seattle-it-working-to-address-july-dashcam-data-loss/" /].

[Callout text:"634.8" caption:"Hours of footage lost due to dropped frames" /]

Even though the system was piloted starting in 2002 and [link text:"fully deployed by 2007" href:"http://web.archive.org/web/20120726211200/http://www.seattle.gov/police/OPA/Docs/InCar_Video_12_23_2011.pdf" /],
the video data wasn’t available on the City of Seattle’s open data portal [link text:"until 2015" href:"http://komonews.com/news/local/four-years-later-spd-dashcam-library-now-online"/]. 
The portal now contains metadata about every video recorded, and a list of the times when frames were lost by the system. 

##### Hours of footage lost each month due to dropped frames

[SVG src:"svg/overview-1.svg" /]

The chart above shows how many hours of video are lost each month due to frames being dropped by the system. 
The department was aware of the glitch in January of 2014, but didn't report it publicly until that April, 
when it seemed things were under control. 

Unfortunately, the problem wasn't completely solved. There was another spike in dropped frames in September 2014, and 
the problem still continues to this day. Although the problem is less severe now, several hours of video are 
still being lost every month according to the most recent available data.

##### Hours of footage lost each month due to dropped frames since 2015

[SVG src:"svg/overview-recent.svg" /]

Most occurances of frames being lost are relatively short, about 16.5 seconds on average. However, 
loss of longer chunks of video continue to be common. 


##### Frequency of frame drops

[callout text:"65" caption:"Officers missing a block of video 5 minutes or longer" /]

[img src:"images/density.png" /]


Lorem ipsum dolor sit amet, pericula torquatos sit in. Cum dicta corrumpit ei, ne eros lorem hendrerit usu. Munere voluptaria ad vis, nihil primis comprehensam an vix. Eu nec labore consulatu molestiae, nibh clita tation eu sit. Id lucilius convenire est, at mea suas agam detracto. Ea temporibus consectetuer vix, nonumy tincidunt reprimique ex mea.

[br/]
[i]
This document was created with [link href:"https://idyll-lang.github.io/idyll/" text:"Idyll" /], a new markup language for
creating interactive documents. See the [link text:"markup used to create this page" href:"https://github.com/mathisonian/seattle-pd-dashcams/blob/master/index.idl"/].
[/i]

[/section]

